on:
  push:
    branches:
      - main
      - testing-branch

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Builds Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tsc
        uses: icrawl/action-tsc@v1
      - name: how does it look down here?
        run: |
          pwd
          ls -lah
