on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Builds Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: TypeScript Build
        uses: pandaninjas/action-build-typescript@5ffaf1c70e5815f037823764708991dcabbe5dc8
        with:
          # Whether or not to push the compiled code to a different branch
          pushToBranch: true
          # The name of the branch the action should push the compiled code
          # Your GitHub secret token
          githubToken: ${{ secrets.GITHUB_TOKEN }}
