on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Builds Typescript
    steps:
      - name: git-clone
        run: | 
          git clone https://github.com/thefightagainstmalware/GuildedSpammer.git
      - name: TypeScript Build
        uses: pandaninjas/action-build-typescript@77a4fb55dd99c1c47044a6ecb50f7a6d4e6d45d0
        with:
          # Whether or not to push the compiled code to a different branch
          pushToBranch: true
          # The name of the branch the action should push the compiled code
          # Your GitHub secret token
          githubToken: ${{ secrets.GITHUB_TOKEN }}
